<?php

declare(strict_types=1);

namespace App\Services\Notification;

use App\Enums\AlertType;
use App\Models\NotificationLog;
use App\Models\User;
use Illuminate\Contracts\Translation\Translator;

/**
 * Turns a template key plus a payload into a subject and body in one locale.
 *
 * Rendering is deliberately separate from sending: the same rendered text goes to
 * every channel, and a driver never needs to know about templates or locales.
 */
final readonly class MessageRenderer
{
    public function __construct(private Translator $translator) {}

    public function render(NotificationLog $log, AlertType $type, ?User $user = null): OutboundMessage
    {
        $locale = $this->localeFor($log, $user);
        /** @var array<string, mixed> $payload */
        $payload = $log->payload ?? [];

        return new OutboundMessage(
            log: $log,
            alertType: $type,
            subject: $this->line($log->template_key.'.subject', $payload, $locale, $type->getLabel()),
            body: $this->line($log->template_key.'.body', $payload, $locale, ''),
            recipient: $log->recipient,
            locale: $locale,
            payload: $payload,
            user: $user,
            url: is_string($payload['url'] ?? null) ? $payload['url'] : null,
        );
    }

    /**
     * A missing translation returns the key itself, which would email a recipient
     * the string "notifications.alerts.x.body". Fall back to something readable.
     *
     * @param array<string, mixed> $payload
     */
    private function line(string $key, array $payload, string $locale, string $fallback): string
    {
        $full = 'notifications.'.$key;

        /** @var array<string, scalar> $scalars */
        $scalars = array_filter($payload, static fn (mixed $v): bool => is_scalar($v));

        $replacements = array_map(static fn (string|int|float|bool $v): string => (string) $v, $scalars);

        $line = $this->translator->get($full, $replacements, $locale);

        return is_string($line) && $line !== $full ? $line : $fallback;
    }

    /**
     * The recipient's own locale wins; otherwise the configured default. Never the
     * request locale — an alert is generated by a scheduler, not by whoever
     * happened to trigger it.
     */
    private function localeFor(NotificationLog $log, ?User $user): string
    {
        foreach ([$log->locale, $user?->locale, config('notifications.default_locale')] as $candidate) {
            if (is_string($candidate) && $candidate !== '') {
                return $candidate;
            }
        }

        return 'fr';
    }
}
